# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Timeout for commands executed by starship (in milliseconds).
command_timeout = 3600000

# Timeout for starship to scan files (in milliseconds).
scan_timeout = 500

# Define the format/order of prompt elements
format = """(bold white)
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$docker_context\
$python\
$kubernetes\
$aws\
$line_break\
$time\
$character
"""
[character]
success_symbol = '[ ❯](bold green)'
error_symbol = '[ ❯](bold red)'

[python]
pyenv_version_name = true
python_binary = "python"
style = "bold green"

# Show current directory
[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold purple"
format = "[$path]($style)[$read_only]($read_only_style) "

# Show time
[time]
disabled = false
style = "white"
format = "[$time]($style)"

# Disable Terraform workspace and version display
[terraform]
disabled = true

[kubernetes]
disabled = false
symbol = "⎈"
style = "bold blue"
format = '[$symbol](bright-blue) [$context( \($namespace\))]($style) '
